config/routes.rb
Gold::Engine.routes.draw do
  get "/start", to: "setup#new"

  get "/terms", to: "billing#terms", as: "terms"
  put "/terms", to: "billing#process_terms"

  get "/tier", to: "billing#tier", as: "select_tier"
  put "/tier", to: "billing#select_tier"

  get "/charge", to: "billing#outstanding_charge", as: "outstanding_charge"
  get "/charge/process", to: "billing#process_charge", as: "process_charge"
  get "/charge/expired", to: "billing#expired_charge", as: "expired_charge"
  get "/charge/declined", to: "billing#declined_charge", as: "declined_charge"
  get "/charge/missing", to: "billing#missing_charge", as: "missing_charge"
  post "/charge/retry", to: "billing#retry_charge", as: "retry_charge"

  get "/suspended", to: "billing#suspended", as: "suspended"
  get "/unavailable", to: "billing#unavailable", as: "unavailable"

  get "/uninstalled", to: "billing#uninstalled", as: "uninstalled"

  get "/referral", to: "referrals#track", as: "referral"
end

Gold::AdminEngine.routes.draw do
  scope :billing do
    post '/credit', to: 'admin/billing#issue_credit', as: 'issue_credit'
    put '/suspend', to: 'admin/billing#suspend', as: 'suspend'
    put '/unsuspend', to: 'admin/billing#unsuspend', as: 'unsuspend'
    put '/reset_trial_days', to: 'admin/billing#reset_trial_days', as: 'reset_trial_days'
    put '/discount', to: 'admin/billing#apply_discount', as: 'apply_discount'
    put '/transition', to: 'admin/billing#transition', as: 'transition'
    put '/change_tier', to: 'admin/billing#change_tier', as: 'change_tier'
    put '/override_shopify_plan', to: 'admin/billing#override_shopify_plan', as: 'override_shopify_plan'
    delete '/charge/:id', to: 'admin/billing#cancel_charge', as: 'cancel_charge'
  end

  scope :referrals do
    post    "/", to: "admin/referrals#create", as: "referrals"
    patch   "/:id", to: "admin/referrals#update", as: "referral"
    post    "/billings", to: "admin/referrals#add_billing", as: "add_billing_referral"
    delete  "/:id", to: "admin/referrals#delete", as: "delete_referral"
  end
end

app/models/gold/concerns/gilded.rb
require "statesman"

module Gold
  module Concerns
    # This adds all of the necessary bits to an application's shop class for
    # Gold to work properly.
    #
    # Steps to install:
    #
    # 1) Include `Gold::Concerns::Gilded` in the Shop class,
    # 2) Run `rake gold:install:migrations`
    # 3) Run `rake db:migrate`
    #
    module Gilded
      extend ActiveSupport::Concern

      included do
        has_one :billing, class_name: "Gold::Billing", dependent: :destroy
      end
    end
  end
end

app/models/gold/referral.rb
module Gold
  # A referral can be assigned to a billing record, which can be helpful for
  # tracking affiliates with discount codes
  class Referral < ApplicationRecord
    has_many :billings, dependent: :nullify,
                        foreign_key: "gold_referral_id",
                        inverse_of: "referral"

    validates :code, presence: true, uniqueness: true
    validates :discount_percentage, numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 100
    }

    before_validation :ensure_code_format

    private

    def ensure_code_format
      self.code = code.parameterize.underscore.upcase
    end
  end
end

app/models/gold/transition.rb
module Gold
  # Stores transitions between states in Gold::Machine.
  class Transition < ApplicationRecord
    # If your transition table doesn't have the default `updated_at` timestamp column,
    # you'll need to configure the `updated_timestamp_column` option, setting it to
    # another column name (e.g. `:updated_on`) or `nil`.
    #
    # self.updated_timestamp_column = :updated_on
    # self.updated_timestamp_column = nil

    belongs_to :billing, inverse_of: :transitions

    after_destroy :update_most_recent, if: :most_recent?

    private

    def update_most_recent
      last_transition = billing.transitions.order(:sort_key).last
      return if last_transition.blank?

      # rubocop:disable Rails/SkipsModelValidations
      last_transition.update_column(:most_recent, true)
      # rubocop:enable Rails/SkipsModelValidations
    end
  end
end

app/controllers/gold/admin/admin_controller.rb
module Gold
  module Admin
    # Main controller for Gold admin to be used in app
    class AdminController < ApplicationController
      credentials = Gold.configuration.admin_credentials
      http_basic_authenticate_with name: credentials[:user],
                                   password: credentials[:password]
    end
  end
end

app/controllers/gold/admin/billing_controller.rb
module Gold
  module Admin
    # Main controller for Gold to be used in app
    class BillingController < AdminController
      around_action :shopify_session

      rescue_from Statesman::TransitionFailedError,
                  Statesman::GuardFailedError,
                  Gold::Exceptions::MetadataMissing do |e|
        flash[:danger] = e.message
        go_back
      end

      def transition
        transitions = [params[:to]].flatten

        transitions.each do |t|
          billing.transition_to!(t, metadata)
        end

        flash[:success] = "Transitioned to '#{transitions.join(',')}'"
        go_back
      end

      # rubocop:disable Metrics/LineLength:Length
      def change_tier
        tier = Tier.find(params[:tier])

        outcome = SelectTierOp.new(billing, tier).call

        if outcome.is_a?(Outcomes::TierApplied)
          flash[:success] = "Changed billing to '#{tier.name}'"
        elsif outcome.ok?
          charge_outcome = ChargeOp.new(billing, process_charge_url).call

          if charge_outcome.is_a?(Outcomes::ActiveCharge)
            accept_or_decline_outcome = AcceptOrDeclineChargeOp.new(billing, charge_outcome.charge_id).call

            if accept_or_decline_outcome.ok?
              apply_tier_outcome = ApplyTierOp.new(billing).call

              if apply_tier_outcome.ok? # rubocop:disable Metrics/BlockNesting
                flash[:success] = "Changed billing to '#{tier.name}', no merchant action required"
              else
                flash[:danger] = "Failed to apply tier because '#{apply_tier_outcome.reason}'"
              end
            else
              flash[:danger] = "Failed to accept or decline charge because '#{accept_or_decline_outcome.reason}'"
            end
          elsif charge_outcome.is_a?(Outcomes::ChargeNotNeeded)
            flash[:success] = "Applied free tier '#{tier.name}', no merchant action required. You may need to cancel their current charge."
          else
            flash[:warning] = "Changing tier, but merchant action is required before tier is applied"
          end
        else
          flash[:danger] = "Failed to apply tier because '#{outcome.reason}'"
        end

        go_back
      end
      # rubocop:enable Metrics/LineLength:Length

      # Issue a credit to a shop
      def issue_credit
        outcome = IssueCreditOp.new(billing, params[:amount], params[:reason]).call

        if outcome.ok?
          flash["success"] = "Issued credit"
        else
          flash["danger"] = "Failed to issue credit because '#{outcome.message}'"
        end

        go_back
      end

      def cancel_charge
        begin
          charge = ShopifyAPI::RecurringApplicationCharge.find(params[:charge_id])
          charge.cancel
          flash["success"] = "Cancelled charge"
        rescue ActiveResource::ResourceNotFound
          flash["warning"] = "That charge was not found for '#{ShopifyAPI::Base.site}'"
        end

        go_back
      end

      # Suspend a shop
      def suspend
        if params[:confirm_suspend].blank?
          flash[:danger] = "Please confirm you want to suspend this account"
          go_back && return
        end

        SuspendOp.new(billing).call
        flash[:success] = "Account suspended"
        go_back
      end

      # Unsuspend a shop
      def unsuspend
        outcome = UnsuspendOp.new(billing).call

        Gold::ChargeOp.new(billing, process_charge_url).call unless outcome.ok?

        flash[:success] = "Account unsuspended, charge is '#{outcome}'"
        go_back
      end

      def apply_discount
        outcome = ApplyDiscountOp.new(billing,
                                      params[:percentage].to_i,
                                      process_charge_url).call

        if outcome.is_a?(Outcomes::PendingCharge)
          flash[:warning] = "Discount applied, merchant must reauthorize the charge"
        elsif outcome.ok?
          flash[:success] = "Discount updated, will be used for future charges"
        else
          flash[:danger] = "Failed to apply discount because '#{outcome.message}'"
        end

        go_back
      end

      def override_shopify_plan
        plan = params[:plan].presence
        if billing.update(shopify_plan_override: plan)
          flash[:success] = if plan
                              "Changed Shopify plan to '#{plan}'"
                            else
                              "Removed Shopify plan override"
                            end
        else
          flash[:danger] = "Failed to save shop"
        end

        go_back
      end

      def reset_trial_days
        case params[:trial_action]
        when "reset"
          if billing.update(trial_starts_at: Time.current)
            flash[:success] = "New trial starts... now! You might need to" \
                              "cancel their charge first."
          else
            flash[:danger] = "Failed to reset trial days"
          end
        when "clear"
          if billing.update(trial_starts_at: nil)
            flash[:success] = "Trial started over. The merchant will be faced" \
                              "with a new charge upon login."
          else
            flash[:danger] = "Failed to clear trial days"
          end
        else
          flash[:danger] = "Don't know what to do with" \
                          " '#{params[:trial_action]}' trial action"
        end

        go_back
      end

      private

      def shopify_session
        billing.shop.with_shopify_session do
          yield
        end
      end

      def billing
        @billing ||= Billing.find(params[:id])
      end

      def metadata
        md = {
          applied_by: "admin"
        }

        if params.dig(:metadata, :key).present?
          md[params[:metadata][:key]] = params[:metadata][:value]
        end
        md
      end

      def go_back
        redirect_back(fallback_location: main_app.gold_admin_engine_path)
      end
    end
  end
end

app/controllers/gold/admin/referrals_controller.rb
module Gold
  module Admin
    # Controller for referrals
    class ReferralsController < AdminController
      def create
        referral = Referral.new(referral_params)

        if referral.save
          flash[:success] = "Created new referrer"
        else
          message = referral.errors.full_messages.join(", ")
          flash[:danger] = "Failed to create, #{message}"
        end

        redirect_to "#{request.path}/#{referral.id}"
      end

      def update
        referral = Referral.find(params[:id])

        if referral.update(referral_params)
          flash[:success] = "Update referrer"
        else
          message = referral.errors.full_messages.join(", ")
          flash[:danger] = "Failed to update, #{message}"
        end

        redirect_back(fallback_location: "/admin")
      end

      def delete
        referral = Referral.find(params[:id])

        referral.destroy!

        flash[:success] = "Poof! Code #{referral.code} no longer exists"

        redirect_to gold_admin_engine.referrals_path
      end

      def add_billing
        referral = Referral.find_by(id: params[:referral_id])
        billing = Billing.find(params[:billing_id])

        billing.update(referral: referral)

        flash[:success] = "Updated referral"

        redirect_back(fallback_location: "/admin")
      end

      private

      def referral_params
        params.require(:referral).permit(:contact_name,
                                         :contact_email,
                                         :company,
                                         :code,
                                         :discount_percentage)
      end
    end
  end
end

app/controllers/gold/application_controller.rb
module Gold
  # Controller that all Gold controllers inherit from.
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    around_action :catch_halt

    layout "application"

    helper_method :billing

    private

    # Allows an action to stop processing (like `return`, but works even in
    # nested calls) and return a response to the user.
    def catch_halt
      catch(:halt) { yield }
    end
  end
end

app/controllers/gold/authenticated_controller.rb
require "gold/application_controller"

module Gold
  # Inherit from Shopify's authenticated module
  class AuthenticatedController < ApplicationController
    include ShopifyApp::Authenticated
  end
end

app/controllers/gold/concerns/merchant_facing.rb
module Gold
  module Concerns
    # Helpers that make it easier to work with the current merchant's billing
    # information in controllers.
    module MerchantFacing
      def self.included(base)
        base.helper_method :billing
      end

      # Returns the Gold::Billing instance for the currently logged-in merchant.
      def billing
        @billing ||= Billing.find_by!(shop_id: session[:shop_id])
      rescue ActiveRecord::RecordNotFound
        raise Gold::Exceptions::BillingNotFound
      end

      # `before_action` filter that forces a merchant to deal with
      # billing-related states (outstanding charges, acceptance of terms, etc)
      # before continuing with their work.
      def confront_mandatory_billing_action
        ConfrontMandatoryBillingAction.new(self).call
      end

      # Provides access to routes, passing in a particular controller as
      # context. We go through the effort of putting this into a separate class
      # because we do not want to directly include the url helpers into whatever
      # controller we are included into because that might override routes. This
      # solution isolates the Gold routes from whatever routes the app that Gold
      # is embedded in may have defined.
      class HasAccessToRoutes
        include Engine.routes.url_helpers
        delegate :default_url_options, :url_options, to: :@context

        def initialize(context)
          @context = context
          @engine = context.gold_engine
        end
      end

      # See documentation on `confront_mandatory_billing_action`.
      class ConfrontMandatoryBillingAction < HasAccessToRoutes
        def call
          begin
            state = @context.billing.current_state
          rescue ActiveRecord::RecordNotFound
            state = nil
          end

          Gold.logger.info("Confronting billing, state is '#{state}'")

          case state
          when nil, :new, :install
            Gold.logger.info("Redirecting to terms page...")
            return @context.redirect_to(@engine.terms_url)
          when :select_tier, :reinstalled, :accepted_terms
            Gold.logger.info("Redirecting to select tier...")
            return @context.redirect_to(@engine.select_tier_url)
          when :charge_missing
            Gold.logger.info("Redirecting to missing charge...")
            return @context.redirect_to(@engine.missing_charge_url)
          when :sudden_charge, :delayed_charge, :optional_charge
            Gold.logger.info("Redirecting to outstanding charge...")
            return @context.redirect_to(@engine.outstanding_charge_url)
          when :sudden_charge_declined, :delayed_charge_declined
            Gold.logger.info("Redirecting to declined charge...")
            return @context.redirect_to(@engine.declined_charge_url)
          when :sudden_charge_expired, :delayed_charge_expired
            Gold.logger.info("Redirecting to expired charge...")
            return @context.redirect_to(@engine.expired_charge_url)
          when :marked_as_delinquent, :delinquent
            Gold.logger.info("Redirecting to missing charge...")
            return @context.redirect_to(@engine.missing_charge_url)
          when :marked_as_suspended, :suspended
            Gold.logger.info("Redirecting to suspended page...")
            return @context.redirect_to(@engine.suspended_path)
          when :marked_as_uninstalled, :uninstalled, :frozen, :done
            Gold.logger.info("Redirecting to uninstalled page...")
            return @context.redirect_to(@engine.uninstalled_path)
          when :cleanup
            Gold.logger.info("Shop is cleanup, redirecting to unavailable...")
            return @context.redirect_to(@engine.unavailable_path)
          end
        end
      end
    end
  end
end

app/controllers/gold/referrals_controller.rb
module Gold
  # Handles referral tracking
  class ReferralsController < ApplicationController
    def track
      referral = Referral.find_by(code: params[:code])

      cookies[:gold_referral_id] = { value: referral.id, expires: 30.days } if referral

      redirect_to Gold.configuration.app_listing_url
    end
  end
end

app/controllers/gold/setup_controller.rb
module Gold
  class SetupController < ApplicationController
    def new
      tier = Tier.find(params[:tier])
      cookies[:gold_tier_id] = { value: tier.id, expires: 7.days } if tier
      redirect_to Gold.configuration.app_listing_url
    end
  end
end

app/views/gold/billing/_inner_head.html.erb
<%# Override this in your app %>

app/views/gold/billing/declined_charge.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Charge declined
</p>
<p>
  We couldn't process your payment because you declined the charge from Shopify.
</p>
<div style="height: 25px;"></div>

<%= form_tag(retry_charge_path, method: :post) do %>
  <a class="Polaris-Button" href="<%= tier_path %>">Choose a plan</a>
  <span style="padding: 0 10px;">or</span>
  <button 
    type="submit" 
    class="Polaris-Button Polaris-Button--primary">
    <span class="Polaris-Button__Content">
      <span class="Polaris-Button__Text">Try again</span>
    </span>
  </button>
  </p>
<% end %>

app/views/gold/billing/expired_charge.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Your app charge has expired
</p>
<p>Please accept a new charge before continuing.</p>
<div style="height: 25px;"></div>
<%= form_tag(retry_charge_path, method: :post) do %>
  <button 
    type="submit" 
    class="Polaris-Button Polaris-Button--primary">
    <span class="Polaris-Button__Content">
      <span class="Polaris-Button__Text">Try again</span>
    </span>
  </button>
<% end %>

app/views/gold/billing/missing_charge.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Missing app charge
</p>

<p>
  We have checked our records and Shopify's and we cannot find your recurring
  charge for <%= Gold.configuration.app_name %>. The following might prompt you to approve a new charge with
  Shopify. Don't worry, this will replace any existing charge so you won't be
  double-charged.
</p>

<div style="height: 25px;"></div>

<%= form_tag(retry_charge_path, method: :post) do %>
  <button 
    type="submit" 
    class="Polaris-Button Polaris-Button--primary">
    <span class="Polaris-Button__Content">
      <span class="Polaris-Button__Text">Continue</span>
    </span>
  </button>
<% end %>

app/views/gold/billing/outstanding_charge.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Outstanding app charge
</p>

<p>
  Please approve this charge before continuing. You will be redirected to Shopify's billing
  to accept this charge.
</p>

<div style="height: 25px;"></div>

<a class="Polaris-Button Polaris-Button--primary"
   id="confirmation-button"
   href="<%= @confirmation_url %>">View charges</a>

app/views/gold/billing/suspended.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Uh oh! Your store is currently suspended
</p>

<p>
  We should have sent you an email about why your store is suspended. Please 
  reach out to our 
  <a href="mailto:<%= Gold.configuration.contact_email %>" target="_blank">support team</a>
   so we can work with you on a resolution.
</p>

app/views/gold/billing/terms.html.erb
<h1>Terms of Service</h1>

<% if @error %>
  <p class="error">
    You must accept the terms of service before continuing.
  </p>
<% end %>

<p>
  This is where a set of terms and conditions should go.
</p>

<% if @already_accepted %>
  <p>
    You have already accepted these terms.
  </p>
<% else %>
  <%= form_tag(terms_path, method: :put) do %>
    <%= submit_tag "Decline", name: "decline" %>
    <%= submit_tag "Accept", name: "accept" %>
  <% end %>
<% end %>

app/views/gold/billing/tier.html.erb
<h1>Select a Tier</h1>

<p>
  Here are the tiers that are available to you. You can always come back here
  later and choose a different tier.
</p>

<%= form_tag(select_tier_path, method: :put) do %>
  <% @tiers.each do |tier| %>
    <div>
      <% @current_tier = billing.tier == tier %>
      <% @unavailable = !billing.qualifies_for_tier?(tier) %>
      <label>
        <%= radio_button_tag :tier, tier.id, @current_tier, disabled: @unavailable %>
        <%= tier.name %>
        <% if @current_tier && @unavailable %>
          (This your current tier and you have outgrown it with your usage)
        <% elsif @current_tier %>
          (This is your current tier)
        <% elsif @unavailable %>
          (This tier is not available based on your current usage)
        <% end %>
      </label>
    </div>
  <% end %>

  <%= link_to "Cancel", main_app.root_path %>
  <%= submit_tag "Select" %>
<% end %>

app/views/gold/billing/transition_error.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Oops! Request failed
</p>

<p>
  We're sorry, but we couldn't respond to your request. Please
  <a href="<%= shopify_app.logout_path %>" class="Polaris-Link">logout</a>
  and try again in a few minutes. If the problem persists, please reach out to our
  <a class="Polaris-Link" href="mailto:<%= Gold.configuration.contact_email %>">support team</a> and we'll get right on it.
</p>

app/views/gold/billing/unavailable.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  Install unavailable
</p>

<p>Drat! We're sorry, but we couldn't install the app at this time. Please try again in a few minutes or contact our support.</p>
<div style="height: 25px;"></div>
<a class="Polaris-Button" href="<%= shopify_app.login_path %>">Try again</a>
  

app/views/gold/billing/uninstalled.html.erb
<p class="Polaris-DisplayText Polaris-DisplayText--sizeLarge">
  <%= Gold.configuration.app_name %> is uninstalled
</p>


<p>
  It looks like you have uninstalled this app recently or your store was previously frozen.
</p>
<div style="height: 25px;"></div>
<p>
  <a class="Polaris-Button Polaris-Button--primary-button" 
  href="<%= shopify_app.login_path %>">Reinstall</a>
</p>