config/routes.rb
Gold::Engine.routes.draw do
  get "/start", to: "setup#new"

  get "/terms", to: "billing#terms", as: "terms"
  put "/terms", to: "billing#process_terms"

  get "/tier", to: "billing#tier", as: "select_tier"
  put "/tier", to: "billing#select_tier"

  get "/charge", to: "billing#outstanding_charge", as: "outstanding_charge"
  get "/charge/process", to: "billing#process_charge", as: "process_charge"
  get "/charge/expired", to: "billing#expired_charge", as: "expired_charge"
  get "/charge/declined", to: "billing#declined_charge", as: "declined_charge"
  get "/charge/missing", to: "billing#missing_charge", as: "missing_charge"
  post "/charge/retry", to: "billing#retry_charge", as: "retry_charge"

  get "/suspended", to: "billing#suspended", as: "suspended"
  get "/unavailable", to: "billing#unavailable", as: "unavailable"

  get "/uninstalled", to: "billing#uninstalled", as: "uninstalled"

  get "/referral", to: "referrals#track", as: "referral"
end

Gold::AdminEngine.routes.draw do
  scope :billing do
    post '/credit', to: 'admin/billing#issue_credit', as: 'issue_credit'
    put '/suspend', to: 'admin/billing#suspend', as: 'suspend'
    put '/unsuspend', to: 'admin/billing#unsuspend', as: 'unsuspend'
    put '/reset_trial_days', to: 'admin/billing#reset_trial_days', as: 'reset_trial_days'
    put '/discount', to: 'admin/billing#apply_discount', as: 'apply_discount'
    put '/transition', to: 'admin/billing#transition', as: 'transition'
    put '/change_tier', to: 'admin/billing#change_tier', as: 'change_tier'
    put '/override_shopify_plan', to: 'admin/billing#override_shopify_plan', as: 'override_shopify_plan'
    delete '/charge/:id', to: 'admin/billing#cancel_charge', as: 'cancel_charge'
  end

  scope :referrals do
    post    "/", to: "admin/referrals#create", as: "referrals"
    patch   "/:id", to: "admin/referrals#update", as: "referral"
    post    "/billings", to: "admin/referrals#add_billing", as: "add_billing_referral"
    delete  "/:id", to: "admin/referrals#delete", as: "delete_referral"
  end
end

app/models/gold/referral.rb
module Gold
  # A referral can be assigned to a billing record, which can be helpful for
  # tracking affiliates with discount codes
  class Referral < ApplicationRecord
    has_many :billings, dependent: :nullify,
                        foreign_key: "gold_referral_id",
                        inverse_of: "referral"

    validates :code, presence: true, uniqueness: true
    validates :discount_percentage, numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 100
    }

    before_validation :ensure_code_format

    private

    def ensure_code_format
      self.code = code.parameterize.underscore.upcase
    end
  end
end

app/controllers/gold/admin/referrals_controller.rb
module Gold
  module Admin
    # Controller for referrals
    class ReferralsController < AdminController
      def create
        referral = Referral.new(referral_params)

        if referral.save
          flash[:success] = "Created new referrer"
        else
          message = referral.errors.full_messages.join(", ")
          flash[:danger] = "Failed to create, #{message}"
        end

        redirect_to "#{request.path}/#{referral.id}"
      end

      def update
        referral = Referral.find(params[:id])

        if referral.update(referral_params)
          flash[:success] = "Update referrer"
        else
          message = referral.errors.full_messages.join(", ")
          flash[:danger] = "Failed to update, #{message}"
        end

        redirect_back(fallback_location: "/admin")
      end

      def delete
        referral = Referral.find(params[:id])

        referral.destroy!

        flash[:success] = "Poof! Code #{referral.code} no longer exists"

        redirect_to gold_admin_engine.referrals_path
      end

      def add_billing
        referral = Referral.find_by(id: params[:referral_id])
        billing = Billing.find(params[:billing_id])

        billing.update(referral: referral)

        flash[:success] = "Updated referral"

        redirect_back(fallback_location: "/admin")
      end

      private

      def referral_params
        params.require(:referral).permit(:contact_name,
                                         :contact_email,
                                         :company,
                                         :code,
                                         :discount_percentage)
      end
    end
  end
end

app/controllers/gold/referrals_controller.rb
module Gold
  # Handles referral tracking
  class ReferralsController < ApplicationController
    def track
      referral = Referral.find_by(code: params[:code])

      cookies[:gold_referral_id] = { value: referral.id, expires: 30.days } if referral

      redirect_to Gold.configuration.app_listing_url
    end
  end
end

app/views/gold/admin/referrals/_billings.erb
<div class="card mb-3">
  <div class="card-header">
    <strong>Merchants</strong>
  </div>
  <div class="card-body">
    <% if billings.any? %>
      <table class="table celled">
        <thead>
          <tr>
            <th>Domain</th>
            <th>Sign up</th>
            <th>Plan</th>
            <th>Monthly price</th>
            <th>Installed</th>
          </tr>
        </thead>
        <tbody>
          <% billings.each do |billing| %>
            <% shop = billing.shop %>
            <tr>
              <td><%= shop.domain %></td>
              <td><%= time_ago_in_words(shop.created_at) %> ago</td>
              <td><%= billing&.tier&.id %></td>
              <td>
                <%= number_to_currency(shop.monthly_price / 100) %>
              </td>
              <td>
                <% if shop.installed? %>
                  <span class="green">Yes</span>
                <% else %>
                  <span class="red">No</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No shops</p>
    <% end %>
  </div>
</div>

app/views/gold/admin/referrals/_card.erb
<div class="card mb-3">
  <div class="card-header">
    <strong>Referral</strong>
  </div>
  <div class="card-body">
    <aside class="float-right">
      <a data-toggle="collapse" href="#collapseReferral">Change</a>

      <div id="collapseReferral" class="collapse mt-3">
        <%= form_tag(gold_admin_engine.add_billing_referral_path) do %>
          <input type="hidden" name="billing_id" value="<%= billing.id %>">
          <select name="referral_id">
            <option value="">None</option>
            <%= Gold::Referral.all.each do |referral| %>
              <option value="<%= referral.id %>" <% if billing.referral&.id == referral.id %>selected<% end %>><%= referral.code %></option>
            <% end %>
          </select>

          <input type="submit" class="btn btn-primary btn-sm" value="Update">
        <% end %>
      </div>
    </aside>

    <% if billing.referral %>
      <%= link_to(billing.referral.code, admin_referral_path(billing.referral)) %>
    <% else %>
      <p>No referral</p>
    <% end %>
  </div>
</div>

app/views/gold/admin/referrals/_delete.erb
<%= form_for(referral, method: "delete", url: gold_admin_engine.delete_referral_path(referral.id)) do |f| %>
  <%= submit_tag "Delete referral", confirm: "Are you sure want to permanently delete this referral?", class: "btn btn-danger" %>
<% end %>

app/views/gold/admin/referrals/_form.erb
<%= form_for(referral, url: referral.new_record? ? gold_admin_engine.referrals_path : gold_admin_engine.referral_path(referral.id)) do |f| %>
  <div class="form-group">
    <label>Contact name</label>
    <%= f.text_field :contact_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Contact email</label>
    <%= f.email_field :contact_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Company</label>
    <p class="text-muted">Note: if left blank, merchant won't see a "Be sure to thank company" message.</p>
    <%= f.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Code</label>
    <%= f.text_field :code, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Discount percentage</label>
    <%= f.number_field :discount_percentage, class: "form-control", min: 0, max: 100 %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>